include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: warning
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_final_fields: warning
    prefer_final_locals: warning

linter:
  rules:
    # 🧱 Styl kodu
    always_use_package_imports: true
    avoid_print: true
    prefer_single_quotes: true
    sort_constructors_first: false
    unnecessary_this: true
    use_super_parameters: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_redundant_argument_values: true

    # 🧩 Czystość i bezpieczeństwo
    avoid_unnecessary_containers: true
    avoid_init_to_null: true
    use_key_in_widget_constructors: true
    require_trailing_commas: true
    prefer_typing_uninitialized_variables: false
    depend_on_referenced_packages: false
